// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppLink: typeof import('./src/components/AppLink.vue')['default']
    DarkToggleButton: typeof import('./src/components/slides/DarkToggleButton.vue')['default']
    FeatherTwitter: typeof import('~icons/feather/twitter')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Home: typeof import('./src/components/Home/Home.vue')['default']
    ListBookmarks: typeof import('./src/components/ListBookmarks.vue')['default']
    ListNotes: typeof import('./src/components/ListNotes.vue')['default']
    ListPosts: typeof import('./src/components/ListPosts.vue')['default']
    Marker: typeof import('./src/components/slides/Marker.vue')['default']
    MarkerCore: typeof import('./src/components/slides/MarkerCore.vue')['default']
    MarkerPattern: typeof import('./src/components/slides/MarkerPattern.vue')['default']
    MarkerTips: typeof import('./src/components/slides/MarkerTips.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Plum: typeof import('./src/components/Plum.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    RiMoonLine: typeof import('~icons/ri/moon-line')['default']
    RiSunLine: typeof import('~icons/ri/sun-line')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StarsRanking: typeof import('./src/components/StarsRanking.vue')['default']
    SubNav: typeof import('./src/components/SubNav.vue')['default']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
    Tweet: typeof import('./src/components/Tweet.vue')['default']
    VueUseFn: typeof import('./src/components/slides/VueUseFn.vue')['default']
  }
}

export { }
